# Generated by Django 3.2 on 2022-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honey_collector_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='采集人编号')),
                ('honey_collector', models.CharField(blank=True, max_length=50, null=True, verbose_name='采集人')),
                ('collector_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('collector_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('collector_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='地址')),
                ('collector_note', models.TextField(blank=True, null=True, verbose_name='采集人备注')),
            ],
            options={
                'verbose_name': '蜂蜜_采集人信息',
                'verbose_name_plural': '蜂蜜_采集人信息',
            },
        ),
        migrations.CreateModel(
            name='HoneyIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honey_sample_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='蜂蜜编号')),
                ('taxon_species', models.CharField(blank=True, max_length=50, null=True, verbose_name='成份物种名')),
                ('taxon_species_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='成份物种中文名')),
                ('abundance_percentage', models.CharField(blank=True, max_length=50, null=True, verbose_name='丰度百分比')),
            ],
            options={
                'verbose_name': '蜂蜜_成份',
                'verbose_name_plural': '蜂蜜_成份',
            },
        ),
        migrations.CreateModel(
            name='HoneyRefGenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类编号')),
                ('taxon_kingdom', models.CharField(blank=True, max_length=50, null=True, verbose_name='界')),
                ('taxon_kingdom_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='界_中文')),
                ('taxon_phylum', models.CharField(blank=True, max_length=50, null=True, verbose_name='门')),
                ('taxon_phylum_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='门_中文')),
                ('taxon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='纲')),
                ('taxon_class_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='纲_中文')),
                ('taxon_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='目')),
                ('taxon_order_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='目_中文')),
                ('taxon_family', models.CharField(blank=True, max_length=50, null=True, verbose_name='科')),
                ('taxon_family_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='科_中文')),
                ('taxon_genus', models.CharField(blank=True, max_length=50, null=True, verbose_name='属')),
                ('taxon_genus_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='属_中文')),
                ('taxon_species', models.CharField(blank=True, max_length=50, null=True, verbose_name='种')),
                ('taxon_species_chinese', models.CharField(blank=True, max_length=50, null=True, verbose_name='种_中文')),
                ('genomic_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='参考基因组类型')),
                ('data_origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据来源')),
            ],
            options={
                'verbose_name': '蜂蜜_物种参考基因组',
                'verbose_name_plural': '蜂蜜_物种参考基因组',
            },
        ),
        migrations.CreateModel(
            name='HoneySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_site', models.CharField(blank=True, max_length=250, null=True, verbose_name='简要采集地信息')),
                ('surrounding_environment', models.CharField(blank=True, max_length=50, null=True, verbose_name='周边环境')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('altitude', models.IntegerField(blank=True, null=True, verbose_name='海拔')),
                ('honey_bee_origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='蜂种')),
                ('honey_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='蜂蜜类型')),
                ('honey_sample_note', models.TextField(verbose_name='样本备注')),
            ],
            options={
                'verbose_name': '蜂蜜_样品',
                'verbose_name_plural': '蜂蜜_样品',
            },
        ),
    ]
