# Generated by Django 3.2 on 2022-10-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeysample',
            name='honey_sample_note',
            field=models.TextField(blank=True, null=True, verbose_name='样本备注'),
        ),
    ]
