# Generated by Django 3.2 on 2022-10-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencing16s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='菌株编号')),
                ('ab1_quality_16s', models.CharField(blank=True, max_length=50, null=True, verbose_name='16S测序质量')),
                ('mapped_sequence_16s', models.CharField(blank=True, max_length=250, null=True, verbose_name='16S比对到的序列')),
                ('similarity_16s', models.FloatField(blank=True, null=True, verbose_name='16S比对相似度')),
                ('blast_website_16s', models.CharField(blank=True, max_length=250, null=True, verbose_name='16S比对网站')),
                ('data_file_path_16s', models.CharField(blank=True, max_length=250, null=True, verbose_name='16S序列存储位置')),
                ('blast_by_who_16s', models.CharField(blank=True, max_length=50, null=True, verbose_name='16S比对人员')),
            ],
            options={
                'verbose_name': '菌株_16S比对信息',
                'verbose_name_plural': '菌株_16S比对信息',
            },
        ),
    ]
